spring:
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  datasource:
    url: jdbc:postgresql://localhost:5432/english
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  application:
   name: EnglishHelperBot
  redis:
    data:
      host: ${REDIS_HOST:localhost}
bot:
  name: ${TELEGRAM_BOT_USERNAME:}
  token: ${TELEGRAM_BOT_TOKEN:}
#debug: true
#logging:
#  level:
#    org:
#      springframework:
#        web: DEBUG
#    root: DEBUG