package com.learn.english.model;

public enum UserStatus {
    NO_ACTIVITY,
    FILLING_ORIGINAL_WITH_BOT,
    FILLING_TRANSLATION_WITH_BOT,
    FILLING_EXAMPLE_WITH_BOT,
    FILLING_ORIGINAL_WITHOUT_BOT,
    FILLING_TRANSLATION_WITHOUT_BOT,
    FILLING_EXAMPLE_WITHOUT_BOT,
    REPEATING_CHOSE_TRANSLATION,
    REPEATING_CHOOSE_ORIGINAL,
    REPEATING_WRITE_WORD_BY_TRANSLATION,
}
